version: "3.3"
services:
    
    proxy:
        ports:
            - "80:80"
            - "8090:8080"
        command:
            - --providers.docker
            - --providers.docker.constraints=Label(`traefik.constraint-label-stack`, `${TRAEFIK_TAG?Variable not set}`)
            - --providers.docker.exposedbydefault=false
            - --accesslog
            - --log
            - --api
            - --api.insecure=true
        labels:
            - traefik.enable=true
            - traefik.http.routers.${STACK_NAME?Variable not set}-traefik-public-http.rule=Host(`${DOMAIN?Variable not set}`)
            - traefik.http.services.${STACK_NAME?Variable not set}-traefik-public.loadbalancer.server.port=80
    
    pgadmin:
        ports:
            - "5050:5050"

    backend:
        ports:
            - "8888:8888"
        volumes:
            - ./app:/app
        environment: 
            - SERVER_HOST=http://${DOMAIN?Variable not set}
        build: 
            context: .
            args:
                INSTALL_DEV: ${INSTALL_DEV-true}
        command: /start-reload.sh
        labels:
            - traefik.enable=true
            - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
            - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.rule=PathPrefix(`/`) || PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)
            - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=80

networks:
    traefik-public:
        external: false
