version: "3.8"
services:
    backend:
        build: 
            context: .
            args:
                INSTALL_DEV: "true"
        ports:
            - "80:80"
        volumes:
            - .:/app
        command: /start-reload.sh
