version: "3.3"
services:

    proxy:
        ports:
            - "80:80"
            - "8090:8080"
        command:
            - --providers.docker
            - --providers.docker.constraints=Label(`traefik.constraint-label-stack`, `${TRAEFIK_TAG?TRAEFIK_TAG variable not set}`)
            - --providers.docker.exposedbydefault=false
            - --accesslog
            - --log
            - --api
            - --api.insecure=true
        labels:
            - traefik.enable=true
            - traefik.http.routers.${STACK_NAME?STACK_NAME variable not set}-traefik-public-http.rule=Host(`${DOMAIN?DOMAIN variable not set}`)
            - traefik.http.services.${STACK_NAME?STACK_NAME variable not set}-traefik-public.loadbalancer.server.port=80

    pgadmin:
        ports:
            - "5050:5050"

    backend:
        ports:
            - "8888:8888"
            - "5678:5678"
        volumes:
            - ./app:/app
        environment:
            - SERVER_HOST=http://${DOMAIN?DOMAIN variable not set}
        build:
            context: .
            args:
                INSTALL_DEV: ${INSTALL_DEV-true}
        env_file:
            - .env
        command: /start-reload.sh
        labels:
            - traefik.enable=true
            - traefik.constraint-label-stack=${TRAEFIK_TAG?TRAEFIK_TAG variable not set}
            - traefik.http.routers.${STACK_NAME?STACK_NAME variable not set}-backend-http.rule=PathPrefix(`/`)
            - traefik.http.services.${STACK_NAME?STACK_NAME variable not set}-backend.loadbalancer.server.port=80

networks:
    traefik-public:
        external: false
