"""Add initial migration

Revision ID: 8cc7df598021
Revises: 
Create Date: 2020-08-21 22:35:00.714031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8cc7df598021"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("isAvailable", sa.Boolean(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "room_logs",
        sa.Column("room_code", sa.String(), nullable=False),
        sa.Column("player", sa.String(), nullable=False),
        sa.Column("created_time", sa.DateTime(), nullable=False),
        sa.Column("roll", sa.ARRAY(sa.Integer()), nullable=False),
        sa.ForeignKeyConstraint(["room_code"], ["rooms.code"],),
        sa.PrimaryKeyConstraint("room_code", "player", "created_time"),
    )
    op.create_table(
        "room_players",
        sa.Column("room_code", sa.String(), nullable=False),
        sa.Column("player", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["room_code"], ["rooms.code"],),
        sa.PrimaryKeyConstraint("room_code", "player"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room_players")
    op.drop_table("room_logs")
    op.drop_table("rooms")
    # ### end Alembic commands ###
